# Generated by Django 3.2 on 2022-12-18 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('imo_number', models.IntegerField()),
                ('vessel_name', models.CharField(max_length=500)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, default=1, null=True)),
                ('create_datetime', models.DateField(auto_now_add=True)),
                ('update_datetime', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'vessel',
            },
        ),
    ]
